### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by risshun** [strengejacke/strengejacke#1]
```
> devtools::install_github("strengejacke/strengejacke")
Error in read.dcf(path) : 
  Found continuation line starting '             other t ...' at begin of record.
```

**Comment by NilsDroste** [comment]
same here

**Comment by LubomirBednar** [comment]
bump

**Comment by strengejacke** [comment]
Is this still an issue? I have revised the code quite a lot and committed some updates the past days.

**Comment by LubomirBednar** [comment]
Good morning.
Unfortunately I've been tied up with a lot of organisational and office
work, so I didn't have a chance to try it yet. I'll let you know when I get
back to mu data analysis and run it.

With kind regards

Lubomir Bednar, PhD student, BSc, MSc.

Humboldt-Universität zu Berlin (HU)
Institute of Biology
Molecular Parasitology
Philippstraße 13 (Haus 14)
10115 Berlin
Germany

Email: bednarlu@hu-berlin.de
Tel:  +4915257330508

       +420605506006


Leibniz-Institut für Zoo- und Wildtierforschung (IZW)
im Forschungsverbund Berlin e.V.
Alfred-Kowalke-Straße 17
10315 Berlin
Germany

Email: bednar@izw-berlin.de

Tel:  +4915257330508

       +420605506006
